(function(global){
  const css = `
    *{box-sizing:border-box}
    body{margin:0;background:#eef3fa;color:#10213d;font-family:Arial,Helvetica,sans-serif;font-size:10px;line-height:1.28}
    .no-print{position:fixed;right:18px;top:14px;z-index:10}.no-print button{background:#0f3d91;color:white;border:0;border-radius:10px;padding:10px 14px;font-weight:900;box-shadow:0 8px 20px rgba(0,0,0,.18)}
    .sheet{width:210mm;min-height:297mm;margin:12px auto;background:white;padding:8mm 9.5mm;box-shadow:0 8px 28px rgba(15,37,80,.18);page-break-after:always}
    .ct-header{display:grid;grid-template-columns:1.15fr 1.15fr .85fr;gap:9px;align-items:stretch;border-bottom:3px solid #123a78;padding-bottom:6px;margin-bottom:7px}
    .ct-brand{display:flex;align-items:center;gap:8px}.ct-logo{width:68px;max-height:42px;object-fit:contain}.ct-brand h1{font-size:13px;margin:0;color:#123a78;letter-spacing:.01em}.ct-brand p{margin:1px 0;color:#50627f}.ct-brand .small{font-size:8.5px;color:#7b8aa1}
    .ct-title{text-align:center;border-left:1px solid #d7e1ef;border-right:1px solid #d7e1ef;padding:2px 6px}.ct-title h2{font-size:17px;margin:2px 0 1px;text-transform:uppercase;letter-spacing:.04em;color:#10213d}.ct-title p{margin:0;color:#667891}.doc-code{display:inline-block;border-radius:999px;background:#eaf1fb;color:#123a78;font-weight:900;padding:3px 8px;font-size:8.2px;text-transform:uppercase}
    .ct-meta{border:1px solid #cbd8ea;border-radius:8px;background:#f8fbff;padding:5px;display:grid;grid-template-columns:1fr;gap:1px;text-align:right}.ct-meta span{font-size:7.6px;text-transform:uppercase;color:#62748d}.ct-meta b{font-size:9.5px;color:#123a78}
    .hero-decision{border-radius:14px;border:2px solid;padding:9px 10px;display:grid;grid-template-columns:72px 1fr 135px;gap:10px;align-items:center;margin:7px 0}.hero-decision.ok{background:#eaf8ef;border-color:#3aa860;color:#0b6628}.hero-decision.bad{background:#fff0f0;border-color:#c95858;color:#990000}.hero-decision.warn{background:#fff8e7;border-color:#d39a26;color:#805400}.hero-decision .check{font-size:38px;font-weight:900;text-align:center}.hero-decision .big{font-size:25px;font-weight:900;letter-spacing:.06em}.hero-decision .line{font-size:9.2px;color:#394b65}.hero-decision .mini{text-align:right;border-left:1px solid rgba(0,0,0,.15);padding-left:8px}.hero-decision .mini b{font-size:12px}.hero-decision .mini span{display:block;color:#4b5e77;font-size:8.2px;text-transform:uppercase}
    .grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-bottom:6px}.grid-3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin-bottom:6px}.grid-4{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:6px}
    .card{border:1px solid #cbd8ea;border-radius:8px;padding:6px;background:#fff;break-inside:avoid}.card h3{font-size:9.4px;margin:0 0 5px;color:#123a78;text-transform:uppercase;letter-spacing:.045em}.card.compact{padding:5px}.card.blue{background:#f7fbff}.card.soft{background:#fbfdff}
    .kv,.results{width:100%;border-collapse:collapse}.kv th,.kv td{border-bottom:1px solid #e6edf6;padding:3px 3px;vertical-align:top}.kv th{width:39%;text-align:left;color:#60708a;text-transform:uppercase;font-size:7.8px}.kv td{font-weight:800}.kv tr:last-child th,.kv tr:last-child td{border-bottom:0}
    .results th,.results td{border:1px solid #d4dfef;padding:4px;text-align:right}.results th:first-child,.results td:first-child{text-align:left}.results thead th{background:#e9f0fb;color:#123a78;text-transform:uppercase;font-size:8.5px}.results tr.mean-row td{background:#edf6ff;font-weight:900}.results tr.total-row td{background:#f1fff4;font-weight:900}
    .trace-chain{display:grid;grid-template-columns:1fr 32px 1fr 32px 1fr;gap:4px;align-items:stretch}.trace-arrow{display:flex;align-items:center;justify-content:center;color:#123a78;font-size:22px;font-weight:900}.trace-card{border:1px solid #d4dfef;border-radius:10px;padding:7px;min-height:104px;background:#f9fbfe}.trace-card h4{margin:0 0 4px;color:#123a78;text-transform:uppercase;font-size:8.8px}.trace-card .role{display:inline-block;border-radius:999px;padding:2px 6px;background:#eaf1fb;color:#123a78;font-weight:900;font-size:7.5px;margin-bottom:4px}.trace-card.pattern{border-color:#3aa860;background:#f2fff6}.trace-card.accessory{border-color:#6aa7d8;background:#f6fbff}.trace-card.instrument{border-color:#123a78;background:#f8fbff}.trace-status{font-weight:900;margin:2px 0 4px}.pattern .trace-status{color:#0b6628}.accessory .trace-status{color:#245b8c}.instrument .trace-status{color:#123a78}
    .decision{border-radius:12px;text-align:center;padding:10px;border:2px solid;margin:7px 0}.decision.ok{background:#eaf8ef;border-color:#3aa860;color:#0b6628}.decision.bad{background:#fff0f0;border-color:#c95858;color:#990000}.decision.warn{background:#fff8e7;border-color:#d39a26;color:#805400}.decision .big{font-size:28px;font-weight:900;letter-spacing:.06em}.decision .text{font-size:9px;color:#394b65}
    .annex-title{text-align:center;margin:4px 0 7px}.annex-title h2{margin:0;text-transform:uppercase;letter-spacing:.05em;font-size:15px}.annex-title p{margin:2px 0;color:#667891}.formula-list{display:grid;grid-template-columns:1fr 1fr;gap:5px}.formula{border:1px solid #e1e8f2;border-radius:8px;background:#fbfdff;padding:5px}.formula b{color:#123a78}.formula code{display:block;margin-top:2px;background:#eef4fb;border-radius:5px;padding:3px;font-family:Arial,Helvetica,sans-serif;color:#10213d}
    .obs{background:#fff9ec;border-left:4px solid #d48a00;border-radius:8px;padding:6px}.obs ul{margin:0 0 0 15px;padding:0;line-height:1.35}.sign{display:grid;grid-template-columns:1fr 1fr 1fr;gap:18px;margin-top:14px}.sig{border-top:1px solid #10213d;text-align:center;padding-top:5px;color:#60708a}.sig b{display:block;color:#10213d}
    .footer{border-top:1px solid #d4dfef;margin-top:7px;padding-top:5px;display:grid;grid-template-columns:1.4fr 1fr .55fr;gap:6px;color:#60708a;font-size:7.8px}.footer b{color:#123a78}.footer .center{text-align:center}.footer .right{text-align:right}
    .qr{display:flex;gap:7px;align-items:center;justify-content:center}.qr-grid{width:52px;height:52px;display:grid;grid-template-columns:repeat(7,1fr);grid-template-rows:repeat(7,1fr);gap:1px;background:#e7edf6;padding:3px}.qr-grid span{background:white}.qr-grid span.on{background:#123a78}.muted{color:#60708a}.tag{display:inline-block;border-radius:999px;padding:3px 8px;font-size:8.2px;font-weight:900;background:#edf3fb;color:#123a78;margin:2px}.declaration{font-size:9px;color:#394b65;line-height:1.36}.page-break{page-break-before:always}.photo-box{height:62px;border:1px dashed #a9b8cf;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#60708a;background:#f8fbff}.summary-kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-bottom:6px}.kpi{background:#f8fbff;border:1px solid #d4dfef;border-radius:8px;padding:5px;text-align:center}.kpi span{display:block;text-transform:uppercase;font-size:7.4px;color:#60708a}.kpi b{font-size:11px;color:#123a78}
    @media print{body{background:white}.sheet{box-shadow:none;margin:0;width:auto;min-height:297mm}.no-print{display:none}}
  `;
  global.TMPCertificateLayout = {
    VERSION:'CT001_REV_A_LAYOUT',
    document(html,title){ return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${global.TMPCertUtils.esc(title)}</title><style>${css}</style></head><body><div class="no-print"><button onclick="window.print()">Imprimir / guardar PDF</button></div>${html}</body></html>`; },
    sheet(content, extra=''){ return `<section class="sheet ${extra}">${content}</section>`; }
  };
})(window);
